### ISSUE TITLE
Listening on wrong port

### ISSUE THREAD

**Issue by Bmooij** [theolivenbaum/electron-sharp#21]
* **Version**:  27.0.1.43128

* **Target**: Windows

Steps to Reproduce:

1. Change Electron.NET to ElectronSharp
2. run `electron-sharp start`

After I run the start command, nothing happens. 
It looks like it is listening on the wrong port:
```
Electron Socket IO Port: 8000
Electron Socket started on port 8000 at ::1
.NET Core Port: undefined
stdout: Use Electron Port: 8000

stdout: info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
```

**Comment by Cav-jj** [comment]
"aspCoreBackendPort": "random",

**Comment by Bmooij** [comment]
Thanks that fixes my issue!
