### ISSUE TITLE
net8.0 Button Click event wont fire

### ISSUE THREAD

**Issue by Cav-jj** [theolivenbaum/electron-sharp#22]
from project 27.1.0.43644 to with net8.0 click with a button wont fire in blazor going back to using 27.1.0.43604 with net7.0 works

**Comment by Cav-jj** [comment]
It was that one needed to add BrowserWindowOptions -> WebPreferences -> AllowRunningInsecureContent set to true it's set to false as default in dotnet 8.0

**Comment by theolivenbaum** [comment]
@Cav-jj can I close the issue then?
